services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile

    env_file:
      - ../.env

    container_name: sb-canada-dict

    ports:
      - "7860:7860"

    volumes:
      - ../:/app

    restart: unless-stopped

    networks:
      - sb-canada-dict

networks:
  sb-canada-dict:
